#!/usr/bin/env bash

export BASH_LOCAL_LINE="[[ -r ~/.bash_local ]] && source ~/.bash_local"
# Copy files to home directory
for file in *; do cp $file ~/.$file; done

# Add sourcing of bash_local
if [[ grep $BASH_LOCAL_LINE ~/.bashrc ]]; then
  cat >> ~/.bashrc <<EOF
  $BASH_LOCAL_LINE
EOF

  # Update the environment
  source ~/.bashrc
fi

